In [6]:
import pandas as pd, numpy as np
np.random.seed(101)
n=1025
couriers = ['FedEx','UPS','DHL Express','USPS','Estafeta','Redpack','Paquete Express','OnTrac','LaserShip','FedEx Freight','UPS Ground','UPS Air','USPS Priority','DHL Parcel','FEDEX','ups','dhl','estafeta ','  DHL',None]
products = ['Shea Butter Soap','Charcoal Body Soap','Lavender Scent Spray','Rose Scent Mist','Cocoa Body Lotion','Aloe Body Lotion 500ml','Healing Balm','Lip Balm Strawberry','Vanilla Body Soap Bar','Mango Body Lotion','Jasmine Scent Oil','Menthol Balm']

df=pd.DataFrame({
'Shipment_ID':[f'HNT-{np.random.randint(10000,90000)}' for _ in range(n)],
'Order_Date':np.random.choice(['2023-01-15','15/02/2023','2023/03/10','2023-13-40','01-05-2024',None],n),
'Origin_Warehouse':np.random.choice(['Los Angeles, CA','Dallas TX','Miami FL','Mexico City','Guadalajara MX',None],n),
'Destination_State':np.random.choice(['California','CA','Texas','NY','Florida','Jalisco','CDMX','Nuevo Leon','Yucatan',None],n),
'Destination_Country':np.random.choice(['USA','Mexico'],n),
'Customer_Name':np.random.choice(['Sephora USA','Ulta Beauty','Liverpool MX','Walmart Mexico','Target','Amazon',None],n),
'Product_Category':np.random.choice(['Soap','Body Lotion','Scent','Body Soap','Balm','soap','SOAP'],n),
'Product_Name':np.random.choice(products,n),
'Quantity_Units':np.random.choice([10,50,100,200,-5,None,9999],n),
'Courier':np.random.choice(couriers,n),
'Shipping_Cost_USD':np.random.choice(['$250','300','$-50','USD 450',None,'$'],n),
'Delivery_Status':np.random.choice(['Delivered','In Transit','Delayed','Cancelled',None],n),
'Delay_Days':np.random.choice([0,1,2,5,None,100],n),
})
df=pd.concat([df, df.sample(70, random_state=5)]).sample(frac=1, random_state=42).iloc[:1025]
df.to_csv('hunter_final_all_couriers.csv', index=False)
print("Created -", df.shape)

Created - (1025, 13)

In [7]:
df.head()

,Shipment_ID,Order_Date,Origin_Warehouse,Destination_State,Destination_Country,Customer_Name,Product_Category,Product_Name,Quantity_Units,Courier,Shipping_Cost_USD,Delivery_Status,Delay_Days
533,HNT-41291,2023/03/10,None,Florida,Mexico,Sephora USA,Soap,Jasmine Scent Oil,None,DHL,$-50,In Transit,None
139,HNT-33177,2023-13-40,"Los Angeles, CA",Florida,Mexico,Walmart Mexico,Body Soap,Aloe Body Lotion 500ml,200,DHL Parcel,300,None,5
88,HNT-14056,None,Dallas TX,CA,USA,Liverpool MX,Soap,Jasmine Scent Oil,50,FedEx Freight,None,In Transit,100
841,HNT-20383,15/02/2023,Miami FL,NY,USA,Amazon,Scent,Shea Butter Soap,None,FedEx,$250,Delivered,1
985,HNT-28395,2023-13-40,Guadalajara MX,Florida,Mexico,Sephora USA,Balm,Menthol Balm,10,LaserShip,$,In Transit,0

In [8]:
df.duplicated().sum()
df.shape

(1025, 13)

In [9]:
df=df.drop_duplicates()

In [10]:
df.shape

(964, 13)

In [11]:
def set_category(name):
    name=str(name).lower()
    if 'soap' in name:
        return 'Body Soap' if 'body' in name else 'Soap'
    if 'lotion' in name:
        return 'Body Lotion'
    if 'scent' in name or 'jasmine' in name:
        return 'Scent'
    if 'balm'in name:
        return "Balm"
    return name

In [12]:
df['Product_Category']=df['Product_Name'].apply(set_category)

In [13]:
df.head(20)

,Shipment_ID,Order_Date,Origin_Warehouse,Destination_State,Destination_Country,Customer_Name,Product_Category,Product_Name,Quantity_Units,Courier,Shipping_Cost_USD,Delivery_Status,Delay_Days
533,HNT-41291,2023/03/10,None,Florida,Mexico,Sephora USA,Scent,Jasmine Scent Oil,None,DHL,$-50,In Transit,None
139,HNT-33177,2023-13-40,"Los Angeles, CA",Florida,Mexico,Walmart Mexico,Body Lotion,Aloe Body Lotion 500ml,200,DHL Parcel,300,None,5
88,HNT-14056,None,Dallas TX,CA,USA,Liverpool MX,Scent,Jasmine Scent Oil,50,FedEx Freight,None,In Transit,100
841,HNT-20383,15/02/2023,Miami FL,NY,USA,Amazon,Soap,Shea Butter Soap,None,FedEx,$250,Delivered,1
985,HNT-28395,2023-13-40,Guadalajara MX,Florida,Mexico,Sephora USA,Balm,Menthol Balm,10,LaserShip,$,In Transit,0
575,HNT-32040,None,"Los Angeles, CA",NY,USA,Amazon,Body Soap,Charcoal Body Soap,None,FEDEX,300,Delivered,0
286,HNT-13943,None,"Los Angeles, CA",CDMX,Mexico,None,Body Lotion,Aloe Body Lotion 500ml,50,DHL,300,Delivered,5
602,HNT-68379,2023/03/10,Dallas TX,Nuevo Leon,USA,Liverpool MX,Scent,Jasmine Scent Oil,100,UPS,$-50,In Transit,None
23,HNT-73083,2023/03/10,Dallas TX,Nuevo Leon,Mexico,Amazon,Balm,Menthol Balm,200,DHL Express,USD 450,Cancelled,5
715,HNT-67358,15/02/2023,None,California,Mexico,Sephora USA,Body Lotion,Aloe Body Lotion 500ml,-5,UPS Air,$250,Delayed,1
926,HNT-40251,01-05-2024,Guadalajara MX,None,Mexico,Amazon,Body Lotion,Cocoa Body Lotion,200,DHL Express,None,In Transit,1
948,HNT-25230,2023-01-15,Miami FL,Texas,Mexico,None,Body Lotion,Aloe Body Lotion 500ml,None,Estafeta,$,In Transit,5
997,HNT-81671,None,"Los Angeles, CA",Texas,Mexico,Ulta Beauty,Body Lotion,Aloe Body Lotion 500ml,200,USPS,$,In Transit,100
599,HNT-36166,01-05-2024,Mexico City,Florida,Mexico,Walmart Mexico,Body Soap,Vanilla Body Soap Bar,10,Paquete Express,300,Delayed,100
567,HNT-89612,2023-01-15,Miami FL,CDMX,USA,Liverpool MX,Scent,Lavender Scent Spray,50,FedEx Freight,$-50,Delivered,2
675,HNT-57419,01-05-2024,Miami FL,NY,Mexico,Amazon,Body Soap,Vanilla Body Soap Bar,-5,FedEx,$,Delivered,0
543,HNT-80023,15/02/2023,Miami FL,Nuevo Leon,USA,Ulta Beauty,Scent,Rose Scent Mist,10,FedEx,300,In Transit,0
519,HNT-60736,15/02/2023,"Los Angeles, CA",Texas,Mexico,Liverpool MX,Body Soap,Vanilla Body Soap Bar,50,Paquete Express,$,Delayed,0
765,HNT-70478,01-05-2024,Miami FL,Nuevo Leon,USA,Liverpool MX,Scent,Lavender Scent Spray,10,Paquete Express,$,Cancelled,0
767,HNT-74138,2023/03/10,Guadalajara MX,California,Mexico,Ulta Beauty,Soap,Shea Butter Soap,50,FedEx Freight,None,In Transit,5

In [14]:
df[['Product_Name','Product_Category']].head()

               Product_Name Product_Category
533       Jasmine Scent Oil            Scent
139  Aloe Body Lotion 500ml      Body Lotion
88        Jasmine Scent Oil            Scent
841        Shea Butter Soap             Soap
985            Menthol Balm             Balm

In [15]:
df.describe()

,Shipment_ID,Order_Date,Origin_Warehouse,Destination_State,Destination_Country,Customer_Name,Product_Category,Product_Name,Quantity_Units,Courier,Shipping_Cost_USD,Delivery_Status,Delay_Days
count,964,795,820,867,964,828,964,964,826,918,797,793,823
unique,956,5,5,9,2,6,5,12,6,19,5,4,5
top,HNT-30463,2023-13-40,Dallas TX,Texas,Mexico,Amazon,Body Lotion,Aloe Body Lotion 500ml,100,UPS Air,USD 450,In Transit,100
freq,2,165,182,113,486,149,256,96,148,57,166,203,180

In [16]:
df.describe(include='all')

,Shipment_ID,Order_Date,Origin_Warehouse,Destination_State,Destination_Country,Customer_Name,Product_Category,Product_Name,Quantity_Units,Courier,Shipping_Cost_USD,Delivery_Status,Delay_Days
count,964,795,820,867,964,828,964,964,826,918,797,793,823
unique,956,5,5,9,2,6,5,12,6,19,5,4,5
top,HNT-30463,2023-13-40,Dallas TX,Texas,Mexico,Amazon,Body Lotion,Aloe Body Lotion 500ml,100,UPS Air,USD 450,In Transit,100
freq,2,165,182,113,486,149,256,96,148,57,166,203,180

In [17]:
df.columns

Index(['Shipment_ID', 'Order_Date', 'Origin_Warehouse', 'Destination_State',
       'Destination_Country', 'Customer_Name', 'Product_Category',
       'Product_Name', 'Quantity_Units', 'Courier', 'Shipping_Cost_USD',
       'Delivery_Status', 'Delay_Days'],
      dtype='object')

In [18]:
df.describe()

,Shipment_ID,Order_Date,Origin_Warehouse,Destination_State,Destination_Country,Customer_Name,Product_Category,Product_Name,Quantity_Units,Courier,Shipping_Cost_USD,Delivery_Status,Delay_Days
count,964,795,820,867,964,828,964,964,826,918,797,793,823
unique,956,5,5,9,2,6,5,12,6,19,5,4,5
top,HNT-30463,2023-13-40,Dallas TX,Texas,Mexico,Amazon,Body Lotion,Aloe Body Lotion 500ml,100,UPS Air,USD 450,In Transit,100
freq,2,165,182,113,486,149,256,96,148,57,166,203,180

In [19]:
df['Quantity_Units']<0

533    False
139    False
88     False
841    False
985    False
       ...
520    False
838     True
64     False
812    False
14     False
Name: Quantity_Units, Length: 964, dtype: bool

In [20]:
df[df['Quantity_Units']<0]

,Shipment_ID,Order_Date,Origin_Warehouse,Destination_State,Destination_Country,Customer_Name,Product_Category,Product_Name,Quantity_Units,Courier,Shipping_Cost_USD,Delivery_Status,Delay_Days
715,HNT-67358,15/02/2023,None,California,Mexico,Sephora USA,Body Lotion,Aloe Body Lotion 500ml,-5,UPS Air,$250,Delayed,1
675,HNT-57419,01-05-2024,Miami FL,NY,Mexico,Amazon,Body Soap,Vanilla Body Soap Bar,-5,FedEx,$,Delivered,0
44,HNT-87428,2023/03/10,Mexico City,Nuevo Leon,Mexico,Target,Balm,Menthol Balm,-5,LaserShip,300,Delayed,1
388,HNT-37074,01-05-2024,"Los Angeles, CA",None,USA,Ulta Beauty,Balm,Healing Balm,-5,DHL Parcel,300,Cancelled,5
86,HNT-65801,None,Dallas TX,CDMX,Mexico,None,Scent,Lavender Scent Spray,-5,Redpack,300,Delivered,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,HNT-10436,15/02/2023,Miami FL,Texas,USA,Target,Soap,Shea Butter Soap,-5,UPS Ground,$250,Delivered,0
779,HNT-47469,2023-13-40,Guadalajara MX,CA,USA,None,Body Soap,Vanilla Body Soap Bar,-5,dhl,$,In Transit,2
674,HNT-58363,2023-13-40,Guadalajara MX,None,USA,Ulta Beauty,Body Lotion,Cocoa Body Lotion,-5,FEDEX,USD 450,Cancelled,2
391,HNT-35288,None,Dallas TX,None,USA,Sephora USA,Balm,Menthol Balm,-5,FEDEX,$-50,Delayed,100
838,HNT-57042,15/02/2023,Guadalajara MX,California,Mexico,Liverpool MX,Body Lotion,Aloe Body Lotion 500ml,-5,Paquete Express,None,Delivered,0

In [21]:
df.dtypes

Shipment_ID            object
Order_Date             object
Origin_Warehouse       object
Destination_State      object
Destination_Country    object
Customer_Name          object
Product_Category       object
Product_Name           object
Quantity_Units         object
Courier                object
Shipping_Cost_USD      object
Delivery_Status        object
Delay_Days             object
dtype: object

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 964 entries, 533 to 14
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Shipment_ID          964 non-null    object
 1   Order_Date           795 non-null    object
 2   Origin_Warehouse     820 non-null    object
 3   Destination_State    867 non-null    object
 4   Destination_Country  964 non-null    object
 5   Customer_Name        828 non-null    object
 6   Product_Category     964 non-null    object
 7   Product_Name         964 non-null    object
 8   Quantity_Units       826 non-null    object
 9   Courier              918 non-null    object
 10  Shipping_Cost_USD    797 non-null    object
 11  Delivery_Status      793 non-null    object
 12  Delay_Days           823 non-null    object
dtypes: object(13)
memory usage: 105.4+ KB

In [23]:
df['Quantity_Units']=pd.to_numeric(df['Quantity_Units'],errors='coerce')

In [24]:
df['Quantity_Units'].dtype

dtype('float64')

In [25]:
df['Quantity_Units']=df['Quantity_Units'].abs()

In [26]:
df['Quantity_Units'].head()

533      NaN
139    200.0
88      50.0
841      NaN
985     10.0
Name: Quantity_Units, dtype: float64

In [27]:
med=df['Quantity_Units'].median()

In [28]:
print(df['Quantity_Units'].median())

100.0

In [29]:
df['Quantity_Units']=df['Quantity_Units'].fillna(med)

In [30]:
df['Quantity_Units'].head()

533    100.0
139    200.0
88      50.0
841    100.0
985     10.0
Name: Quantity_Units, dtype: float64

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 964 entries, 533 to 14
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Shipment_ID          964 non-null    object
 1   Order_Date           795 non-null    object
 2   Origin_Warehouse     820 non-null    object
 3   Destination_State    867 non-null    object
 4   Destination_Country  964 non-null    object
 5   Customer_Name        828 non-null    object
 6   Product_Category     964 non-null    object
 7   Product_Name         964 non-null    object
 8   Quantity_Units       964 non-null    float64
 9   Courier              918 non-null    object
 10  Shipping_Cost_USD    797 non-null    object
 11  Delivery_Status      793 non-null    object
 12  Delay_Days           823 non-null    object
dtypes: float64(1), object(12)
memory usage: 105.4+ KB

In [32]:
df['Shipping_Cost_USD'].head(15)

533       $-50
139        300
88        None
841       $250
985          $
575        300
286        300
602       $-50
23     USD 450
715       $250
926       None
948          $
997          $
599        300
567       $-50
Name: Shipping_Cost_USD, dtype: object

In [33]:
df['Shipping_Cost_USD']=df['Shipping_Cost_USD'].astype(str).str.replace('$','',regex=False)

In [34]:
df['Shipping_Cost_USD']=df['Shipping_Cost_USD'].str.replace('None','',regex=False)

In [35]:
df['Shipping_Cost_USD']=df['Shipping_Cost_USD'].str.upper().str.replace('USD','',regex=False)

In [36]:
df['Shipping_Cost_USD'].head(15)

533     -50
139     300
88
841     250
985
575     300
286     300
602     -50
23      450
715     250
926
948
997
599     300
567     -50
Name: Shipping_Cost_USD, dtype: object

In [37]:
df['Shipping_Cost_USD']=pd.to_numeric(df['Shipping_Cost_USD'],errors='coerce')

In [38]:
df['Shipping_Cost_USD']=df['Shipping_Cost_USD'].abs()

In [39]:
df['Shipping_Cost_USD']=df['Shipping_Cost_USD'].fillna(df['Shipping_Cost_USD'].median())

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 964 entries, 533 to 14
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Shipment_ID          964 non-null    object
 1   Order_Date           964 non-null    datetime64[ns]
 2   Origin_Warehouse     820 non-null    object
 3   Destination_State    867 non-null    object
 4   Destination_Country  964 non-null    object
 5   Customer_Name        828 non-null    object
 6   Product_Category     964 non-null    object
 7   Product_Name         964 non-null    object
 8   Quantity_Units       964 non-null    float64
 9   Courier              918 non-null    object
 10  Shipping_Cost_USD    964 non-null    float64
 11  Delivery_Status      793 non-null    object
 12  Delay_Days           823 non-null    object
dtypes: datetime64[ns](1), float64(2), object(10)
memory usage: 105.4+ KB

In [41]:
df['Order_Date']=pd.to_datetime(df['Order_Date'],errors='coerce')

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 964 entries, 533 to 14
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Shipment_ID          964 non-null    object
 1   Order_Date           964 non-null    datetime64[ns]
 2   Origin_Warehouse     964 non-null    object
 3   Destination_State    867 non-null    object
 4   Destination_Country  964 non-null    object
 5   Customer_Name        828 non-null    object
 6   Product_Category     964 non-null    object
 7   Product_Name         964 non-null    object
 8   Quantity_Units       964 non-null    float64
 9   Courier              918 non-null    object
 10  Shipping_Cost_USD    964 non-null    float64
 11  Delivery_Status      793 non-null    object
 12  Delay_Days           964 non-null    int64
dtypes: datetime64[ns](1), float64(2), int64(1), object(9)
memory usage: 105.4+ KB

In [44]:
df['Order_Date'].isna().sum()

np.int64(811)

In [45]:
df['Order_Date']=df['Order_Date'].fillna(df['Order_Date'].median())

In [47]:
df.head(20)

,Shipment_ID,Order_Date,Origin_Warehouse,Destination_State,Destination_Country,Customer_Name,Product_Category,Product_Name,Quantity_Units,Courier,Shipping_Cost_USD,Delivery_Status,Delay_Days
533,HNT-41291,2023-03-10,None,Florida,Mexico,Sephora USA,Scent,Jasmine Scent Oil,100.0,DHL,50.0,In Transit,None
139,HNT-33177,2023-03-10,"Los Angeles, CA",Florida,Mexico,Walmart Mexico,Body Lotion,Aloe Body Lotion 500ml,200.0,DHL Parcel,300.0,None,5
88,HNT-14056,2023-03-10,Dallas TX,CA,USA,Liverpool MX,Scent,Jasmine Scent Oil,50.0,FedEx Freight,300.0,In Transit,100
841,HNT-20383,2023-03-10,Miami FL,NY,USA,Amazon,Soap,Shea Butter Soap,100.0,FedEx,250.0,Delivered,1
985,HNT-28395,2023-03-10,Guadalajara MX,Florida,Mexico,Sephora USA,Balm,Menthol Balm,10.0,LaserShip,300.0,In Transit,0
575,HNT-32040,2023-03-10,"Los Angeles, CA",NY,USA,Amazon,Body Soap,Charcoal Body Soap,100.0,FEDEX,300.0,Delivered,0
286,HNT-13943,2023-03-10,"Los Angeles, CA",CDMX,Mexico,None,Body Lotion,Aloe Body Lotion 500ml,50.0,DHL,300.0,Delivered,5
602,HNT-68379,2023-03-10,Dallas TX,Nuevo Leon,USA,Liverpool MX,Scent,Jasmine Scent Oil,100.0,UPS,50.0,In Transit,None
23,HNT-73083,2023-03-10,Dallas TX,Nuevo Leon,Mexico,Amazon,Balm,Menthol Balm,200.0,DHL Express,450.0,Cancelled,5
715,HNT-67358,2023-03-10,None,California,Mexico,Sephora USA,Body Lotion,Aloe Body Lotion 500ml,5.0,UPS Air,250.0,Delayed,1
926,HNT-40251,2023-03-10,Guadalajara MX,None,Mexico,Amazon,Body Lotion,Cocoa Body Lotion,200.0,DHL Express,300.0,In Transit,1
948,HNT-25230,2023-03-10,Miami FL,Texas,Mexico,None,Body Lotion,Aloe Body Lotion 500ml,100.0,Estafeta,300.0,In Transit,5
997,HNT-81671,2023-03-10,"Los Angeles, CA",Texas,Mexico,Ulta Beauty,Body Lotion,Aloe Body Lotion 500ml,200.0,USPS,300.0,In Transit,100
599,HNT-36166,2023-03-10,Mexico City,Florida,Mexico,Walmart Mexico,Body Soap,Vanilla Body Soap Bar,10.0,Paquete Express,300.0,Delayed,100
567,HNT-89612,2023-03-10,Miami FL,CDMX,USA,Liverpool MX,Scent,Lavender Scent Spray,50.0,FedEx Freight,50.0,Delivered,2
675,HNT-57419,2023-03-10,Miami FL,NY,Mexico,Amazon,Body Soap,Vanilla Body Soap Bar,5.0,FedEx,300.0,Delivered,0
543,HNT-80023,2023-03-10,Miami FL,Nuevo Leon,USA,Ulta Beauty,Scent,Rose Scent Mist,10.0,FedEx,300.0,In Transit,0
519,HNT-60736,2023-03-10,"Los Angeles, CA",Texas,Mexico,Liverpool MX,Body Soap,Vanilla Body Soap Bar,50.0,Paquete Express,300.0,Delayed,0
765,HNT-70478,2023-03-10,Miami FL,Nuevo Leon,USA,Liverpool MX,Scent,Lavender Scent Spray,10.0,Paquete Express,300.0,Cancelled,0
767,HNT-74138,2023-03-10,Guadalajara MX,California,Mexico,Ulta Beauty,Soap,Shea Butter Soap,50.0,FedEx Freight,300.0,In Transit,5

In [60]:
df['Delay_Days'].unique()[:10]

array([  2,   5, 100,   1,   0])

In [58]:
df['Delay_Days'].nunique()

5

In [56]:
df['Delay_Days'].value_counts()

Delay_Days
2.0      301
100.0    180
0.0      171
5.0      164
1.0      148
Name: count, dtype: int64

In [54]:
df['Delay_Days']=pd.to_numeric(df['Delay_Days'],errors='coerce')

In [55]:
df['Delay_Days']=df['Delay_Days'].fillna(df['Delay_Days'].median())

In [59]:
df['Delay_Days']=df['Delay_Days'].astype(int)

In [65]:
df['Origin_Warehouse'].value_counts(dropna=False).head(20)

Origin_Warehouse
Dallas TX          182
Miami FL           165
Los Angeles, CA    163
Mexico City        161
Guadalajara MX     149
None               144
Name: count, dtype: int64

In [64]:
df['Origin_Warehouse'].isna().sum()

np.int64(144)

In [66]:
print(df['Origin_Warehouse'].mode())

0    Dallas TX
Name: Origin_Warehouse, dtype: object

In [67]:
print(df['Origin_Warehouse'].mode()[0])

Dallas TX

In [69]:
df['Origin_Warehouse'].mode()[0]

'Dallas TX'

In [71]:
df['Origin_Warehouse']=df['Origin_Warehouse'].fillna(df['Origin_Warehouse'].mode()[0])

In [73]:
df['Destination_State'].isna().sum()

np.int64(97)

In [83]:
df['Destination_State'].value_counts(dropna=False)

Destination_State
TEXAS         210
CALIFORNIA    188
FLORIDA       106
NEWYORK        97
YUCATAN        95
NUEVO LEON     94
CDMX           89
JALISCO        85
Name: count, dtype: int64

In [78]:
df['Destination_State']=df['Destination_State'].fillna(df['Destination_State'].mode()[0])

In [80]:
df['Destination_State']=df['Destination_State'].str.upper()

In [82]:
df['Destination_State']=df['Destination_State'].replace({'NY':'NEWYORK','CA':'CALIFORNIA'})

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 964 entries, 533 to 14
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Shipment_ID          964 non-null    object
 1   Order_Date           964 non-null    datetime64[ns]
 2   Origin_Warehouse     964 non-null    object
 3   Destination_State    964 non-null    object
 4   Destination_Country  964 non-null    object
 5   Customer_Name        964 non-null    object
 6   Product_Category     964 non-null    object
 7   Product_Name         964 non-null    object
 8   Quantity_Units       964 non-null    float64
 9   Courier              964 non-null    object
 10  Shipping_Cost_USD    964 non-null    float64
 11  Delivery_Status      964 non-null    object
 12  Delay_Days           964 non-null    int64
dtypes: datetime64[ns](1), float64(2), int64(1), object(9)
memory usage: 105.4+ KB

In [87]:
df['Customer_Name'].info()

<class 'pandas.core.series.Series'>
Index: 964 entries, 533 to 14
Series name: Customer_Name
Non-Null Count  Dtype
--------------  -----
828 non-null    object
dtypes: object(1)
memory usage: 15.1+ KB

In [89]:
df['Customer_Name'].isna().sum()

np.int64(136)

In [91]:
(df['Customer_Name']=="").sum()

np.int64(0)

In [92]:
df['Customer_Name']=df['Customer_Name'].fillna('Unknown')

In [94]:
df['Courier']=df['Courier'].fillna(df['Courier'].mode()[0])

In [95]:
df['Delivery_Status']=df['Delivery_Status'].fillna(df['Delivery_Status'].mode()[0])

In [97]:
df['Quantity_Units']=df['Quantity_Units'].astype(int)

In [100]:
df.head(15)

,Shipment_ID,Order_Date,Origin_Warehouse,Destination_State,Destination_Country,Customer_Name,Product_Category,Product_Name,Quantity_Units,Courier,Shipping_Cost_USD,Delivery_Status,Delay_Days
0,HNT-41291,2023-03-10,Dallas TX,FLORIDA,Mexico,Sephora USA,Scent,Jasmine Scent Oil,100,DHL,50.0,In Transit,2
1,HNT-33177,2023-03-10,"Los Angeles, CA",FLORIDA,Mexico,Walmart Mexico,Body Lotion,Aloe Body Lotion 500ml,200,DHL Parcel,300.0,Cancelled,5
2,HNT-14056,2023-03-10,Dallas TX,CALIFORNIA,USA,Liverpool MX,Scent,Jasmine Scent Oil,50,FedEx Freight,300.0,In Transit,100
3,HNT-20383,2023-03-10,Miami FL,NEWYORK,USA,Amazon,Soap,Shea Butter Soap,100,FedEx,250.0,Delivered,1
4,HNT-28395,2023-03-10,Guadalajara MX,FLORIDA,Mexico,Sephora USA,Balm,Menthol Balm,10,LaserShip,300.0,In Transit,0
5,HNT-32040,2023-03-10,"Los Angeles, CA",NEWYORK,USA,Amazon,Body Soap,Charcoal Body Soap,100,FEDEX,300.0,Delivered,0
6,HNT-13943,2023-03-10,"Los Angeles, CA",CDMX,Mexico,Unknown,Body Lotion,Aloe Body Lotion 500ml,50,DHL,300.0,Delivered,5
7,HNT-68379,2023-03-10,Dallas TX,NUEVO LEON,USA,Liverpool MX,Scent,Jasmine Scent Oil,100,UPS,50.0,In Transit,2
8,HNT-73083,2023-03-10,Dallas TX,NUEVO LEON,Mexico,Amazon,Balm,Menthol Balm,200,DHL Express,450.0,Cancelled,5
9,HNT-67358,2023-03-10,Dallas TX,CALIFORNIA,Mexico,Sephora USA,Body Lotion,Aloe Body Lotion 500ml,5,UPS Air,250.0,Delayed,1
10,HNT-40251,2023-03-10,Guadalajara MX,TEXAS,Mexico,Amazon,Body Lotion,Cocoa Body Lotion,200,DHL Express,300.0,In Transit,1
11,HNT-25230,2023-03-10,Miami FL,TEXAS,Mexico,Unknown,Body Lotion,Aloe Body Lotion 500ml,100,Estafeta,300.0,In Transit,5
12,HNT-81671,2023-03-10,"Los Angeles, CA",TEXAS,Mexico,Ulta Beauty,Body Lotion,Aloe Body Lotion 500ml,200,USPS,300.0,In Transit,100
13,HNT-36166,2023-03-10,Mexico City,FLORIDA,Mexico,Walmart Mexico,Body Soap,Vanilla Body Soap Bar,10,Paquete Express,300.0,Delayed,100
14,HNT-89612,2023-03-10,Miami FL,CDMX,USA,Liverpool MX,Scent,Lavender Scent Spray,50,FedEx Freight,50.0,Delivered,2

In [99]:
df=df.reset_index(drop=True)

In [101]:
df.to_csv('hunter_cleaned.csv',index=False)

In [102]:
df.shape

(964, 13)

In [103]:
df.isna().sum()

Shipment_ID            0
Order_Date             0
Origin_Warehouse       0
Destination_State      0
Destination_Country    0
Customer_Name          0
Product_Category       0
Product_Name           0
Quantity_Units         0
Courier                0
Shipping_Cost_USD      0
Delivery_Status        0
Delay_Days             0
dtype: int64

In [104]:
df.dtypes

Shipment_ID                    object
Order_Date             datetime64[ns]
Origin_Warehouse               object
Destination_State              object
Destination_Country            object
Customer_Name                  object
Product_Category               object
Product_Name                   object
Quantity_Units                  int64
Courier                        object
Shipping_Cost_USD             float64
Delivery_Status                object
Delay_Days                      int64
dtype: object

In [109]:
total_shipments=len(df)